# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: '3.7'

services:
  greengrass:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws-iot-greengrass
    image: x86_64/aws-iot-greengrass:2.5.4
